### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by ChanyBeck** [ChanyBeck/Hangman#2]

**Comment by ghost** [comment]
Please add the wireframe to the repo as an image.

**Comment by ChanyBeck** [comment]
It's a PNG, is that not good?

**Comment by ghost** [comment]
Yes, but add it to repo in docs folder.

**Comment by ChanyBeck** [comment]
C:\Users\adas\source\repos\Hangman\Docs
This is my file extension

**Comment by ghost** [comment]
You didn't push it to GitHub.

**Comment by ChanyBeck** [comment]
sorry about that, is it good now?

**Comment by shmielminz** [comment]
It's not pushed.

**Comment by ChanyBeck** [comment]
This is my git status 

C:\Users\adas\source\repos\Hangman> git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   Docs/Hangman Wireframe1.PNG
        modified:   Docs/Hangman.docx
        new file:   RecordKeepper/RecordKeepper.sln
        new file:   RecordKeepper/RecordKeepper/Form1.Designer.cs
        new file:   RecordKeepper/RecordKeepper/Form1.cs
        new file:   RecordKeepper/RecordKeepper/Form1.resx
        new file:   RecordKeepper/RecordKeepper/Program.cs
        new file:   RecordKeepper/RecordKeepper/RecordKeepper.csproj

**Comment by ghost** [comment]
>new file: Docs/Hangman Wireframe1.PNG
modified: Docs/Hangman.docx

**Comment by ChanyBeck** [comment]
C:\Users\adas\source\repos\Hangman>git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

**Comment by ghost** [comment]
Now it's pushed. Add a project and add all issues to the project. Also add me as a collaborator to the project.
